### PR TITLE
fix: not getting actual aggregate name

### LINKED ISSUE #99: Fix getting derive name as aggregate name instead of actual one

### PR DESCRIPTION
**Pull request by dawumnam**
closes #99

### CODE REVIEW

File: ruva-macro/src/message.rs [hunk 1]
```diff
@@ -87,9 +89,20 @@ pub(crate) fn get_aggregate_metadata(ast: &mut DeriveInput) -> (TokenStream, Str
 				let quote = quote!(
 					ruva::static_assertions::assert_impl_any!(#tokens: ruva::prelude::Aggregate);
 				);
+
+				tokens.clone().into_iter().for_each(|t| {
```
Comment (Migorithm) [inline ruva-macro/src/message.rs:93]: You hit the right spot! 

@dawumnam
